server:
  port: 8070

logging:
  level:
    org.springframework.web: INFO
    guru.springframework.controllers: INFO
    br.com.votacao: TRACE
    org.hibernate: INFO
    org.springframework.security: INFO