spring:
  jpa:
    show-sql: false
    generate-ddl: false
    hibernate.ddl-auto: validate
    properties:
      hibernate:
        generate_statistics: false
  h2:
    console:
      path: /h2
      enabled: false
logging:
  level:
    org.springframework.web: INFO
    guru.springframework.controllers: INFO
    br.com.votacao: INFO
    org.hibernate: INFO
    org.springframework.security: INFO