server:
  port: 8070
spring:
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate.ddl-auto: update
    properties:
      hibernate:
        generate_statistics: true
        format_sql: true
  h2:
    console:
      path: /h2
      enabled: false
logging:
  level:
    org.springframework.web: INFO
    guru.springframework.controllers: INFO
    br.com.votacao: TRACE
    org.hibernate: INFO
    org.springframework.security: INFO